import { NextRequest, NextResponse } from "next/server";
import { addPurchase, generateOrderNumber } from "@/lib/user";
import { getPatternBySlug } from "@/lib/patterns";
import { sendPatternEmail } from "@/lib/email";

// Dynamic import to avoid build errors if Stripe is not installed
async function getStripe() {
  if (!process.env.STRIPE_SECRET_KEY) {
    throw new Error("STRIPE_SECRET_KEY not configured");
  }
  const Stripe = (await import("stripe")).default;
  return new Stripe(process.env.STRIPE_SECRET_KEY, {
    apiVersion: "2025-02-24.acacia",
  });
}

const webhookSecret = process.env.STRIPE_WEBHOOK_SECRET || "";

export async function POST(request: NextRequest) {
  if (!process.env.STRIPE_SECRET_KEY) {
    return NextResponse.json(
      { error: "Stripe not configured" },
      { status: 500 }
    );
  }

  const stripeInstance = await getStripe();
  const body = await request.text();
  const signature = request.headers.get("stripe-signature")!;

  let event: any;

  try {
    event = stripeInstance.webhooks.constructEvent(body, signature, webhookSecret);
  } catch (err) {
    console.error("Webhook signature verification failed:", err);
    return NextResponse.json(
      { error: "Webhook signature verification failed" },
      { status: 400 }
    );
  }

  // Handle the checkout.session.completed event
  if (event.type === "checkout.session.completed") {
    const session = event.data.object;

    try {
      // Get order details from metadata
      const orderNumber = session.metadata?.orderNumber || generateOrderNumber();
      const patternSlugs = JSON.parse(session.metadata?.patternSlugs || "[]");
      const userId = session.metadata?.userId || "";

      // Build purchase items
      const purchaseItems = patternSlugs.map((item: { slug: string; quantity: number }) => {
        const pattern = getPatternBySlug(item.slug);
        return {
          patternSlug: item.slug,
          patternName: pattern?.name || item.slug,
          quantity: item.quantity,
          price: pattern?.price || 0,
        };
      });

      const total = purchaseItems.reduce(
        (sum: number, item: { price: number; quantity: number }) =>
          sum + item.price * item.quantity,
        0
      );

      // Create purchase record
      const purchase = {
        id: session.id,
        orderNumber,
        date: new Date().toISOString(),
        items: purchaseItems,
        total,
        status: "completed" as const,
        pdfDownloadUrl: `/download/${orderNumber}`, // Will be generated by email service
      };

      // Save purchase - if user is logged in, save to their history
      // Otherwise, purchase will be linked via email when user logs in later
      try {
        addPurchase(purchase);
      } catch (error) {
        // If user not logged in, purchase will be sent via email
        console.log("Purchase saved for email:", session.customer_email);
      }

      // Send email with PDF patterns
      if (session.customer_email) {
        console.log("Webhook: sending email to", session.customer_email, "order", orderNumber);
        await sendPatternEmail({
          email: session.customer_email,
          orderNumber,
          items: purchaseItems,
        });
        console.log("Webhook: sendPatternEmail completed");
      } else {
        console.log("Webhook: no customer_email on session, skipping email");
      }

      return NextResponse.json({ received: true });
    } catch (error) {
      console.error("Error processing webhook:", error);
      return NextResponse.json(
        { error: "Error processing webhook" },
        { status: 500 }
      );
    }
  }

  return NextResponse.json({ received: true });
}
